In [1]:
import numpy as np

In [2]:
#Numpy - Array Manipulation.

In [3]:
arr = np.random.randint(1,10 , (4,4))

In [4]:
arr

array([[5, 5, 2, 3],
       [2, 8, 5, 8],
       [4, 5, 9, 5],
       [8, 5, 1, 4]])

In [5]:
arr.reshape(8,2)

array([[5, 5],
       [2, 3],
       [2, 8],
       [5, 8],
       [4, 5],
       [9, 5],
       [8, 5],
       [1, 4]])

In [6]:
arr

array([[5, 5, 2, 3],
       [2, 8, 5, 8],
       [4, 5, 9, 5],
       [8, 5, 1, 4]])

In [7]:
arr.T

array([[5, 2, 4, 8],
       [5, 8, 5, 5],
       [2, 5, 9, 1],
       [3, 8, 5, 4]])

In [8]:
arr.flatten()

array([5, 5, 2, 3, 2, 8, 5, 8, 4, 5, 9, 5, 8, 5, 1, 4])

In [9]:
arr

array([[5, 5, 2, 3],
       [2, 8, 5, 8],
       [4, 5, 9, 5],
       [8, 5, 1, 4]])

In [11]:
np.expand_dims(arr,axis=1)

array([[[5, 5, 2, 3]],

       [[2, 8, 5, 8]],

       [[4, 5, 9, 5]],

       [[8, 5, 1, 4]]])

In [12]:
np.expand_dims(arr,axis=0)

array([[[5, 5, 2, 3],
        [2, 8, 5, 8],
        [4, 5, 9, 5],
        [8, 5, 1, 4]]])

In [13]:
data = np.array([[1] , [2] , [3]])

In [14]:
np.squeeze(data)

array([1, 2, 3])

In [16]:
np.repeat(data,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [18]:
np.roll(data,2)

array([[2],
       [3],
       [1]])

In [20]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [21]:
#Numpy - Binary Operators.

In [23]:
arr1 = np.random.randint(1,10 , (3,4))
arr2 = np.random.randint(1,10 , (3,4))

In [24]:
arr1

array([[1, 6, 7, 9],
       [3, 4, 4, 2],
       [7, 9, 6, 9]])

In [25]:
arr2

array([[5, 8, 9, 1],
       [2, 8, 8, 4],
       [6, 8, 5, 2]])

In [26]:
arr1+arr2

array([[ 6, 14, 16, 10],
       [ 5, 12, 12,  6],
       [13, 17, 11, 11]])

In [27]:
arr1*arr2

array([[ 5, 48, 63,  9],
       [ 6, 32, 32,  8],
       [42, 72, 30, 18]])

In [28]:
arr1/arr2

array([[0.2       , 0.75      , 0.77777778, 9.        ],
       [1.5       , 0.5       , 0.5       , 0.5       ],
       [1.16666667, 1.125     , 1.2       , 4.5       ]])

In [29]:
arr1-arr2

array([[-4, -2, -2,  8],
       [ 1, -4, -4, -2],
       [ 1,  1,  1,  7]])

In [30]:
arr1**arr2

array([[       1,  1679616, 40353607,        9],
       [       9,    65536,    65536,       16],
       [  117649, 43046721,     7776,       81]])

In [31]:
~arr1

array([[ -2,  -7,  -8, -10],
       [ -4,  -5,  -5,  -3],
       [ -8, -10,  -7, -10]])

In [32]:
arr1

array([[1, 6, 7, 9],
       [3, 4, 4, 2],
       [7, 9, 6, 9]])

In [33]:
arr1>arr2

array([[False, False, False,  True],
       [ True, False, False, False],
       [ True,  True,  True,  True]])

In [34]:
#Numpy - String Functions.

In [35]:
arr = np.array(["sudh" , "kumar"])

In [36]:
arr

array(['sudh', 'kumar'], dtype='<U5')

In [37]:
np.char.upper(arr)

array(['SUDH', 'KUMAR'], dtype='<U5')

In [38]:
np.char.capitalize(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [39]:
np.char.title(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [40]:
#Numpy - Mathematical Functions.

In [41]:
arr1

array([[1, 6, 7, 9],
       [3, 4, 4, 2],
       [7, 9, 6, 9]])

In [42]:
np.sin(arr1)

array([[ 0.84147098, -0.2794155 ,  0.6569866 ,  0.41211849],
       [ 0.14112001, -0.7568025 , -0.7568025 ,  0.90929743],
       [ 0.6569866 ,  0.41211849, -0.2794155 ,  0.41211849]])

In [43]:
np.cos(arr1)

array([[ 0.54030231,  0.96017029,  0.75390225, -0.91113026],
       [-0.9899925 , -0.65364362, -0.65364362, -0.41614684],
       [ 0.75390225, -0.91113026,  0.96017029, -0.91113026]])

In [44]:
np.tan(arr1)

array([[ 1.55740772, -0.29100619,  0.87144798, -0.45231566],
       [-0.14254654,  1.15782128,  1.15782128, -2.18503986],
       [ 0.87144798, -0.45231566, -0.29100619, -0.45231566]])

In [45]:
np.log10(arr1)

array([[0.        , 0.77815125, 0.84509804, 0.95424251],
       [0.47712125, 0.60205999, 0.60205999, 0.30103   ],
       [0.84509804, 0.95424251, 0.77815125, 0.95424251]])

In [46]:
np.exp(arr1)

array([[2.71828183e+00, 4.03428793e+02, 1.09663316e+03, 8.10308393e+03],
       [2.00855369e+01, 5.45981500e+01, 5.45981500e+01, 7.38905610e+00],
       [1.09663316e+03, 8.10308393e+03, 4.03428793e+02, 8.10308393e+03]])

In [47]:
np.power(arr1,2)

array([[ 1, 36, 49, 81],
       [ 9, 16, 16,  4],
       [49, 81, 36, 81]])

In [48]:
np.mean(arr1
       )

5.583333333333333

In [49]:
np.median(arr1)

6.0

In [51]:
np.std(arr1)

2.6601482832520613

In [52]:
np.var(arr1)

7.076388888888889

In [53]:
np.min(arr1)

1

In [54]:
np.max(arr1)

9

In [55]:
#Numpy - Arithmetic Operations.

In [56]:
arr1

array([[1, 6, 7, 9],
       [3, 4, 4, 2],
       [7, 9, 6, 9]])

In [57]:
arr2

array([[5, 8, 9, 1],
       [2, 8, 8, 4],
       [6, 8, 5, 2]])

In [58]:
arr1-arr2

array([[-4, -2, -2,  8],
       [ 1, -4, -4, -2],
       [ 1,  1,  1,  7]])

In [59]:
np.subtract(arr1,arr2)

array([[-4, -2, -2,  8],
       [ 1, -4, -4, -2],
       [ 1,  1,  1,  7]])

In [60]:
np.multiply(arr1,arr2)

array([[ 5, 48, 63,  9],
       [ 6, 32, 32,  8],
       [42, 72, 30, 18]])

In [61]:
np.mod(arr1,arr2)

array([[1, 6, 7, 0],
       [1, 4, 4, 2],
       [1, 1, 1, 1]])

In [62]:
np.power(arr1,arr2)

array([[       1,  1679616, 40353607,        9],
       [       9,    65536,    65536,       16],
       [  117649, 43046721,     7776,       81]])

In [63]:
np.sqrt(arr1)

array([[1.        , 2.44948974, 2.64575131, 3.        ],
       [1.73205081, 2.        , 2.        , 1.41421356],
       [2.64575131, 3.        , 2.44948974, 3.        ]])

In [64]:
#Numpy - Statistical Functions.

In [66]:
arr1

array([[1, 6, 7, 9],
       [3, 4, 4, 2],
       [7, 9, 6, 9]])

In [67]:
np.mean(arr1)

5.583333333333333

In [68]:
np.std(arr1)

2.6601482832520613

In [69]:
np.median(arr1)

6.0