In [1]:
import numpy as np 

In [2]:
l = [1,2,3,4,5]

In [4]:
arr = np.array(l)

In [5]:
type(arr)

numpy.ndarray

In [6]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [8]:
arr1 = np.array([[1,2,3] , [2,3,4]])

In [9]:
arr.ndim

1

In [10]:
arr1.ndim

2

In [11]:
arr

array([1, 2, 3, 4, 5])

In [12]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [14]:
mat = np.matrix(l)

In [15]:
np.asanyarray(l)

array([1, 2, 3, 4, 5])

In [16]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4, 5]])

In [17]:
arr

array([1, 2, 3, 4, 5])

In [18]:
a = arr

In [19]:
a

array([1, 2, 3, 4, 5])

In [20]:
arr

array([1, 2, 3, 4, 5])

In [21]:
arr[0] = 100

In [22]:
arr

array([100,   2,   3,   4,   5])

In [23]:
a

array([100,   2,   3,   4,   5])

In [24]:
b = np.copy(arr)

In [25]:
b

array([100,   2,   3,   4,   5])

In [27]:
b[0] = 234

In [28]:
b

array([234,   2,   3,   4,   5])

In [29]:
arr

array([100,   2,   3,   4,   5])

In [30]:
np.fromfunction(lambda i,j : i==j , (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [31]:
np.fromfunction(lambda i,j : i*j , (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [33]:
list(i*i for i in range(5))

[0, 1, 4, 9, 16]

In [35]:
iterable  = (i*i for i in range(5))

In [36]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [37]:
np.fromstring('23 45 56',sep  = ' ' )

array([23., 45., 56.])

In [38]:
np.fromstring('23,45,56',sep  = ',' )

array([23., 45., 56.])

In [39]:
arr

array([100,   2,   3,   4,   5])

In [40]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [41]:
arr.ndim

1

In [42]:
arr1.ndim

2

In [43]:
arr.size

5

In [44]:
arr1.size

6

In [45]:
arr.shape

(5,)

In [46]:
arr1.shape

(2, 3)

In [48]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [49]:
arr.dtype

dtype('int64')

In [50]:
arr1.dtype

dtype('int64')